urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from generic_views.urls import decorated_includes
import views

app_name = "cobranzas"

urlpatterns = [

    url(r'^aportantes/',
        decorated_includes(
            login_required, views.AportanteList.as_view(namespace="aportantes"))),
    url(r'^panel/$', login_required(views.panel), name="panel"),
    url(r'^test/$', login_required(views.test), name="test"),
    url(r'^periodos/abrir/$',
        login_required(views.abrir_periodo),
        name="abrir-periodo"),
    url(r'^periodos/$', login_required(views.periodos), name="periodos"),
    url(r'^aportantes/cobro/add/$',
        login_required(views.cobro_cuota), name="cobro-add"),
    url(r'^aportantes/gasto/add/$',
        login_required(views.registro_gasto), name="gasto-add"),
    url(r'^aportantes/aportante/show/(?P<aportante_id>\d+)/$',
        login_required(views.aportante_show), name="aportante-show"),
    url(r'^aportantes/aportante/change_profile/$',
        login_required(views.change_profile), name="aportante-change-profile"),
    url(r'^aportantes/aportante/own/$',
        login_required(views.aportante_own), name="aportante-own"),

]

models.py
# -*- coding: utf-8 *-*
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from contable.models import Cuenta, Ejercicio, RegistroAsiento
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from datetime import date
import calendar
import config
from django.utils.functional import cached_property


def DatosIniciales():
    e2016, c = Ejercicio.objects.get_or_create(
        id=1, fecha_inicio="2016-01-01", fecha_fin="2016-12-31", ano=2016)
    for codigo in config.PLAN_DE_CUENTAS:
        nombre = config.PLAN_DE_CUENTAS[codigo][0]
        imputable = config.PLAN_DE_CUENTAS[codigo][1]
        Cuenta.objects.get_or_create(
            codigo=codigo, ejercicio=e2016, nombre=nombre, imputable=imputable)


class Periodo(models.Model):
    class Meta:
        permissions = (
            ("view_periodo", "Puede ver gastos e ingresos de periodos"),
        )

    MES_ENERO = 1
    MES_FEBRERO = 2
    MES_MARZO = 3
    MES_ABRIL = 4
    MES_MAYO = 5
    MES_JUNIO = 6
    MES_JULIO = 7
    MES_AGOSTO = 8
    MES_SEPTIEMBRE = 9
    MES_OCTUBRE = 10
    MES_NOVIEMBRE = 11
    MES_DICIEMBRE = 12

    MES_CHOICES = (
        (MES_ENERO, "Enero"),
        (MES_FEBRERO, "Febrero"),
        (MES_MARZO, "Marzo"),
        (MES_ABRIL, "Abril"),
        (MES_MAYO, "Mayo"),
        (MES_JUNIO, "Junio"),
        (MES_JULIO, "Julio"),
        (MES_AGOSTO, "Agosto"),
        (MES_SEPTIEMBRE, "Septiembre"),
        (MES_OCTUBRE, "Octubre"),
        (MES_NOVIEMBRE, "Noviembre"),
        (MES_DICIEMBRE, "Diciembre"),
    )
    mes = models.PositiveIntegerField(choices=MES_CHOICES)
    ano = models.PositiveIntegerField()

    def __unicode__(self):
        return "%s/%s" % (self.mes, self.ano)

    def first_day(self):
        return date(year=self.ano, month=self.mes, day=1)

    def last_day(self):
        rango = calendar.monthrange(self.ano, self.mes)
        return date(year=self.ano, month=self.mes, day=rango[1])

    @cached_property
    def ejercicio(self):
        eje = Ejercicio.get_ejercicio_by_date(
            self.first_day())
        if eje:
            return eje
        else:
            raise Exception(
                "No hay ejercicio contable asignado a este periodo")

    def get_ejercicio(self):
        return self.ejercicio

    def save(self, *args, **kwargs):
        self.get_ejercicio()  # check if ejercicio is well configured
        s = super(Periodo, self).save(*args, **kwargs)
        return s

    def next(self):
        mes = self.mes
        ano = self.ano
        mes = mes + 1
        if mes > 12:
            ano += 1
            mes = 1
        periodo = Periodo.objects.filter(mes=mes, ano=ano)
        if periodo.count() > 0:
            return periodo[0]
        else:
            return None

    def get_movimientos_gastos(self):
        cuenta_gastos = self.get_ejercicio().cuenta_set.filter(
            codigo=config.CODIGO_CUENTA_GASTOS)
        if cuenta_gastos.count() == 1:
            cuenta_gastos = cuenta_gastos[0]
        else:
            raise Exception(
                "%s: Cuenta Gastos no se encuentra en el plan de cuentas" %
                config.CODIGO_CUENTA_GASTOS)
        gastos = cuenta_gastos.get_movimientos().filter(
            debe__gt=0,
            asiento__imputacion__gte=self.first_day(),
            asiento__imputacion__lte=self.last_day(),
            asiento__tipo=0
        ).order_by("asiento__imputacion")
        return gastos

    def get_movimientos_ingresos(self):
        cuenta_ingresos = self.get_ejercicio().cuenta_set.filter(
            codigo=config.CODIGO_CUENTA_CUOTAS_A_COBRAR)
        if cuenta_ingresos.count() == 1:
            cuenta_ingresos = cuenta_ingresos[0]
        else:
            raise Exception(
                "%s: Cuenta Ingresos no se encuentra en el plan de cuentas" %
                config.CODIGO_CUENTA_CUOTAS_A_COBRAR)

        ingresos = cuenta_ingresos.get_movimientos().filter(
            haber__gt=0,
            asiento__imputacion__gte=self.first_day(),
            asiento__imputacion__lte=self.last_day(),
            asiento__tipo=0
        ).order_by("asiento__imputacion")
        return ingresos

    def get_saldo_disponibilidades(self):
        eje = self.get_ejercicio()
        fecha_fin = self.last_day()
        cuentas = Cuenta.objects.filter(
            ejercicio=eje, codigo__in=config.CODIGOS_CUENTAS_DISPONIBILIDADES)
        ids = list()
        for c in cuentas:
            ids += c.get_rel_ids()
        cuentas = Cuenta.listadoCompleto(
            eje.id, ids=ids, fecha_fin=fecha_fin, tipo__in=(0, 1))
        return cuentas

    def get_otros_activos(self):
        eje = self.get_ejercicio()
        fecha_fin = self.last_day()
        cuentas = Cuenta.objects.filter(
            ejercicio=eje, codigo__in=config.CODIGOS_CUENTAS_OTROS_ACTIVOS)
        ids = list()
        for c in cuentas:
            ids += c.get_rel_ids()
        cuentas = Cuenta.listadoCompleto(
            eje.id, ids=ids, fecha_fin=fecha_fin, tipo__in=(0, 1))
        return cuentas


class Nivel(models.Model):
    nivel = models.CharField(max_length=31)

    def __unicode__(self):
        return self.nivel


@receiver(post_save, sender=User)
def update_user(sender, instance, created, **kwargs):
    if created:
        if instance.email:
            res = Aportante.objects.filter(email=instance.email)
            if res.count() == 1:
                ap = res[0]
                ap.user = instance
                ap.save()
    if (not hasattr(instance, 'aportante') and
       (instance.first_name or instance.last_name)):
        res = Aportante.objects.filter(
            nombres__icontains=instance.first_name,
            apellidos__icontains=instance.last_name,
            user__isnull=True)
        if res.count() == 1:
            ap = res[0]
            ap.user = instance
            ap.save()


class Aportante(models.Model):
    class Meta:
        permissions = (
            ("view_aportante", "Puede ver lista de aportantes"),
        )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True)
    nombres = models.CharField(max_length=63, null=True, blank=True)
    apellidos = models.CharField(max_length=63, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    codigo_cuenta = models.CharField(max_length=13)
    compromiso = models.DecimalField(
        verbose_name='monto mensual', max_digits=18, decimal_places=2)
    nivel = models.ForeignKey(
        Nivel, on_delete=models.SET_NULL, null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    compartir_info = models.BooleanField(default=False)

    fecha_baja = models.DateField(null=True, blank=True)

    def saldo(self):
        cuenta = self.get_cuenta()
        if cuenta:
            return cuenta.saldo.resultado
        else:
            return 0

    def get_cuenta(self):
        if self.codigo_cuenta:
            try:
                cuenta = Cuenta.objects.get(
                    codigo=self.codigo_cuenta,
                    ejercicio=Ejercicio.get_activo())
            except ObjectDoesNotExist:
                return None
            return cuenta
        else:
            return None

    def save(self, *args, **kwargs):
        if self.codigo_cuenta is None or self.codigo_cuenta == "":
            self.codigo_cuenta = self.get_cuenta_padre().get_codigo_siguiente()
            Cuenta.objects.create(
                ejercicio=Ejercicio.get_activo(),
                codigo=self.codigo_cuenta,
                nombre=self.full_name() + " a cobrar",
                imputable=True)
        else:  # TODO: mejorar esto
            cuenta = Cuenta.objects.filter(
                codigo=self.codigo_cuenta, ejercicio=Ejercicio.get_activo())
            if cuenta.count() == 0:
                Cuenta.objects.create(
                    ejercicio=Ejercicio.get_activo(),
                    codigo=self.codigo_cuenta,
                    nombre=self.full_name() + " a cobrar",
                    imputable=True)
        return super(Aportante, self).save(*args, **kwargs)

    def full_name(self):
        if hasattr(self.user, "profile"):
            return self.user.profile.full_name
        else:
            return "%s %s" % (self.nombres, self.apellidos)

    @staticmethod
    def get_cuenta_padre():
        """retorna cual es la cuenta de activo cuotas a cobrar"""
        return config.CUENTA_CUOTAS_A_COBRAR()

    def __unicode__(self):
        return self.full_name()

    def get_movimientos(self):
        acumulado = 0
        cuentas = Cuenta.objects.filter(codigo=self.codigo_cuenta)
        ids = list()
        for c in cuentas:
            ids += c.get_rel_ids()
        ra = RegistroAsiento.objects.filter(cuenta_id__in=ids, asiento__tipo=0)
        movs = ra.order_by("asiento__imputacion", "asiento__numero")
        for m in movs:
            acumulado += m.saldo.resultado
            m.acumulado = acumulado
        return movs

    def get_saldo(self):
        cuenta = Cuenta.objects.get(
            codigo=self.codigo_cuenta, ejercicio=Ejercicio.get_activo())
        return cuenta.saldo

templates/cobranzas/aportante_show.html
{% extends "generic_views/base.html" %}
{% load generic_views_tags %}
{% load render_paginator %}
{% load staticfiles %}
{% block head_extra %}

<link rel="stylesheet" href="{% static 'ace_admin/assets/css/bootstrap-editable.css' %}" />
<link rel="stylesheet" href="{% static 'relaciones/at.js/css/jquery.atwho.css' %}" />
{% endblock %}
{% block page-content %}
<div class="row">
	{% if aportante %}
	{% include "cobranzas/movimientos_list.html" with label=aportante.full_name movimientos=aportante.get_movimientos invertir=False add_url='cobranzas:cobro-add' permissions=perms.cobranzas.add_aportante %}
	{% else %}
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert">
			<i class="ace-icon fa fa-times"></i>
		</button>

		<strong>
			<i class="ace-icon fa fa-times"></i>
			Maldición!
		</strong>

		El administrador todavía no te ha creado la cuenta corriente
		<br>
	</div>
	{% endif %}
</div>
<div class="modal fade in" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" success="">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
{% endblock %}
{% block javascript %}
{% endblock %}

templates/cobranzas/email_cobro.html
{%load contable_extras %}
{%load cobranzas_extras %}
<html lang="en">
	<head>
		
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
	<style type="text/css">


.table-bordered > thead > tr > th, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > tbody > tr > td, .table-bordered > tfoot > tr > td {
    border: 1px solid #dddddd;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #dddddd;
}
th, td, .table-bordered {
    border-radius: 0 !important;
}
td, th {
    padding: 0;
}
.widget-header > .widget-title {
    line-height: 36px;
    padding: 0;
    margin: 0;
    display: inline;
}
h4.smaller {
    font-size: 17px;
}
h4 {
    font-size: 18px;
    font-weight: normal;
    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
h4, .h4 {
    font-size: 18px;
}
h4, .h4, h5, .h5, h6, .h6 {
    margin-top: 10px;
    margin-bottom: 10px;
}
h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
    font-family: inherit;
    font-weight: 500;
    line-height: 1.1;
    color: inherit;
}
.pull-right {
    float: right;
}
.pull-right {
    float: right !important;
}

.widget-header {
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
    position: relative;
    min-height: 38px;
    background: #f7f7f7;
    background-image: -webkit-linear-gradient(top, #ffffff 0%, #eeeeee 100%);
    background-image: -o-linear-gradient(top, #ffffff 0%, #eeeeee 100%);
    background-image: linear-gradient(to bottom, #ffffff 0%, #eeeeee 100%);
    background-repeat: repeat-x;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#ffeeeeee', GradientType=0);
    color: #669fc7;
    border-bottom: 1px solid #DDD;
    padding-left: 12px;
}
.tab-content > .active {
    display: block;
    visibility: visible;
}
.tab-content > .tab-pane {
    display: none;
    visibility: hidden;
}
body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #333333;
    background-color: #ffffff;
}
html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}

.widget-body .table {
    border-top: 1px solid #E5E5E5;
}
th, td, .table-bordered {
    border-radius: 0 !important;
}
.table-bordered {
    border: 1px solid #dddddd;
}
.table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
}
table {
    background-color: transparent;
    border-collapse: collapse;
    border-spacing: 0;
}
.tab-content > .active {
    display: block;
    visibility: visible;
}
.tab-content > .tab-pane {
    display: none;
    visibility: hidden;
}

	</style>

	</head>
	
	<body class="no-skin">
		<p>Se ha registrado el cobro de tu aporte voluntario por $ {{monto|format_dinero}}</p>
        <p>{{descripcion}}</p>
        <p>Tu saldo actual es de: $ {{aportante.get_saldo.resultado|format_dinero}}
        {% if aportante.get_saldo.resultado < 0 %}
            a favor
        {% elif  aportante.get_saldo.resultado > 0 %}
            de deuda
        {% endif %}
        </p>

        <p>Podés revisar tus aportes ingresando a: <a href="{{protocol}}://{{ domain }}">{{protocol}}://{{domain }}</a>
	</body>
</html>

templates/cobranzas/movimientos_list.html
{%load contable_extras %}
{%load cobranzas_extras %}
<div  class="col-lg-6">
	<div class="widget-box" >
		<div class="widget-header">
			<h4 class="widget-title smaller">
			{{label}}
			</h4>
			{% if add_url and permissions != False %}
			<div class="widget-toolbar">
				<a href="{% url add_url %}" data-toggle="modal" data-target="#modal">
					<i class="ace-icon fa fa-plus"></i>
				</a>
			</div>
			{% endif %}
		</div>
		<div class="widget-body">
			<table id="simple-table" class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th>Reg#</th>
						<th>Fecha</th>
						<th>Cuenta</th>
						<th>Concepto</th>
						<th>Monto</th>
					</tr>
				</thead>
				<tbody>
					{% for movi in movimientos %}
					<tr>
						<td>
						<span class="pull-right">
							{% if perms.contable.change_asiento %}
							<a href="{% url 'contable:libro-diario:list' movi.asiento.ejercicio.pk %}?id={{movi.asiento.id}}">
							{% endif %}
							{{movi.asiento.numero}}
							{% if perms.contable.change_asiento %}
							</a>
							{% endif %}
						</span>
						</td>
						<td>{{movi.asiento.imputacion}}</td>
						<td>{{movi.cuenta.nombre}}</td>
						<td>{{movi.asiento.descripcion}}</td>
						<td>
						<span class="pull-right" {% if movi.saldo.resultado|invert:invertir < 0 %}style="color:#F00"{%endif%}>{{movi.saldo.resultado|invert:invertir|format_dinero}}</span>
						</td>
					</tr>
					{%endfor%}
					
				</tbody>
				<tfoot>
				<tr>
					<th colspan="4"><span class="pull-right">Total</span></th>
					<th>
					{% with movimientos|sum  as suma%}
						<span class="pull-right" {% if suma.resultado|invert:invertir < 0 %}style="color:#F00"{%endif%}>
							
							{{ suma.resultado|invert:invertir|format_dinero}}
							
						</span>
					{% endwith %}
					</th>
				</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>

templates/cobranzas/movimientos_table.html
{%load contable_extras %}
{%load cobranzas_extras %}
<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>Fecha</th><th>Nombre</th><th>Concepto</th><th>Monto</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th colspan="3"><span class="pull-right">Total</span></th>
			<th>
				<span class="pull-right">
					{% with movimientos|sum  as suma%}
					{{ suma.resultado|invert:invertir|format_dinero}}
					{% endwith %}
				</span>
			</th>
		</tr>
		{% for ra in movimientos %}
		<tr>
			<td>{{ra.asiento.imputacion}}</td>
			<td>{{ra.cuenta.nombre}}</td>
			<td>
				{{ra.asiento.descripcion}}
			</td>
			<td>
				<span class="pull-right">{{ra.saldo.resultado|invert:invertir|format_dinero}}</span>
			</td>
		</tr>
		{% endfor %}
		</tbody>
		<tfoot>
		<tr>
			<th colspan="3"><span class="pull-right">Total</span></th>
			<th>
				<span class="pull-right">
					{% with movimientos|sum  as suma%}
					{{ suma.resultado|invert:invertir|format_dinero}}
					{% endwith %}
				</span>
			</th>
		</tr>
		</tfoot>
</table>

templates/cobranzas/no_ejercicio.html
{% extends "generic_views/base.html" %}
{% load staticfiles %}
{% block page-content %}
<div class="row">
	<div class="col-lg-6">
		No hay ejercicios contables o no hay cuentas contables. No se puede operar
	</div>
{% endblock %}

templates/cobranzas/panel.html
{% extends "generic_views/base.html" %}
{% load generic_views_tags %}
{% load render_paginator %}
{% load staticfiles %}
{% load contable_extras %}
{% block head_extra %}
<link rel="stylesheet" href="{% static 'ace_admin/assets/css/bootstrap-editable.css' %}" />
<link rel="stylesheet" href="{% static 'relaciones/at.js/css/jquery.atwho.css' %}" />
<script src="{% static 'generic_views/bootstrap-treeview-master/js/bootstrap-treeview.js' %}"></script>
<script src="{% static 'generic_views/tree_view_config.js' %}"></script>
{% endblock %}
{% block page-content %}
<div class="row">
	<div class="col-lg-6">
		<div class="widget-box" >
			<div class="widget-header">
				<h4 class="widget-title smaller">
				Aportantes
				<small>Lista</small>
				</h4>
				{% if perms.cobranzas.change_aportante %}
				<div class="widget-toolbar">
					<a href="{% url 'cobranzas:aportantes:create' %}" data-toggle="modal" data-target="#modal">
						<i class="ace-icon fa fa-plus"></i>
					</a>
				</div>
				{% endif %}
			</div>
			
			<div class="widget-body">
				<table class="table table-striped table-bordered table-hover">
					<thead>
						<tr>
							<th><a href="?order=apellidos">Apellido</a></th>
							<th><a href="?order=nombres">Nombre</a></th>
							<th><a href="?order=aporte">Aporte Mensual</a></th>
							<th><a href="?order=deuda">Deuda</a></th>
							{% if perms.cobranzas.change_aportante %}
							<th></th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
						{% for c in aportantes %}
						<tr>
							<td>{{c.apellidos}}</td>
							<td>{{c.nombres}}</td>
							<td><span class="pull-right">{{c.compromiso}}</span></td>
							<td>
								<span style="{% if c.saldo > 0 %}color:#F00;{% elif c.saldo < 0%}color:#4cae4c;{%endif%}" class="pull-right">{{c.saldo|format_dinero}}</span>
							</td>
							{% if perms.cobranzas.change_aportante %}
							<td>
								<div class="btn-group">
									<button data-toggle="dropdown" class="btn btn-success btn-minier dropdown-toggle">
									<span class="ace-icon fa fa-caret-down icon-only"></span>
									</button>
									<ul class="dropdown-menu dropdown-menu-right">
										<li>
											<a href="{% url 'cobranzas:cobro-add' %}?periodo={{c.last_movimiento.periodo.next.pk}}&aportante={{c.pk}}" data-toggle="modal" data-target="#modal" title="registrar cobro">Registrar Cobro</a>
										</li>
										<li>
											<a href="/cobranzas/aportantes/update/{{c.pk}}/" class="pull-right" data-toggle="modal" data-target="#modal" title="cambiar">Cambiar Aporte Mensual</a>
										</li>
										<li>
											<a href="{%url 'cobranzas:aportante-show' c.id %}">Ver Historial</a>
										</li>
									</ul>
								</div>
							</td>
							{% endif %}
						</tr>
						{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<th colspan="2"><span class="pull-right">Totales:</span></th>
							<th>
								<span class="pull-right">
									{{ total_compromisos|format_dinero}}
								</span>
							</th>
							<th>
								<span style="{% if total_deuda > 0 %}color:#F00;{% elif total_deuda < 0%}color:#4cae4c;{%endif%}" class="pull-right">
									{{ total_deuda|format_dinero}}
								</span>
							</th>
							{% if perms.cobranzas.change_aportante %}
							<th></th>
							{% endif %}
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
	{% include "cobranzas/movimientos_list.html" with label="Útimos Gastos" movimientos=gastos add_url='cobranzas:gasto-add' invertir=False permissions=perms.cobranzas.change_aportante %}
	{% include "cobranzas/movimientos_list.html" with label="Útimos Cobros" movimientos=movimientos add_url='cobranzas:cobro-add' invertir=True permissions=perms.cobranzas.change_aportante %}
	{% url 'contable:plan-de-cuentas:create' ejercicio.id as add_url  %}
	{% include "cobranzas/saldos_list.html" with label="Saldos" cuentas=saldos add_url=add_url permissions=perms.contable.add_asiento %}
</div>
<div class="modal fade in" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" success="">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
{% endblock %}
{% block javascript %}
{% endblock %}

templates/cobranzas/periodos.html
{% extends "generic_views/base.html" %}
{% load generic_views_tags %}
{% load render_paginator %}
{% load contable_extras %}
{% load staticfiles %}
{% block head_extra %}

	
	<link rel="stylesheet" href="{% static 'ace_admin/assets/css/bootstrap-editable.css' %}" />
	<link rel="stylesheet" href="{% static 'relaciones/at.js/css/jquery.atwho.css' %}" />


	<script src="{% static 'generic_views/bootstrap-treeview-master/js/bootstrap-treeview.js' %}"></script>
	<script src="{% static 'generic_views/tree_view_config.js' %}"></script>	

	
{% endblock %}
{% block page-content %}
<div class="row">
	<div class="col-lg-12">
		<!-- #section:elements.tab.option -->
		<div class="tabbable">
			<ul class="nav nav-tabs padding-12 tab-color-blue background-blue" id="myTab4">
				{%for p in periodos %}
				<li>
					<a data-toggle="tab" href="#periodo_{{p.pk}}" aria-expanded="true">{{p.get_mes_display}} {{p.ano}}</a>
				</li>
				{% endfor%}
				<li>
					<a href="{% url 'cobranzas:abrir-periodo' %}" data-toggle="modal" data-target="#modal">
						<i class="fa fa-plus"></i>
					</a>
				</li>
			</ul>
			
			<div class="tab-content">
				{%for p in periodos %}
				<div id="periodo_{{p.pk}}" class="tab-pane">
					<div class="row">
						<div class="col-lg-6">
							<h4>Ingresos Cuotas</h4>
							{% include "cobranzas/movimientos_table.html" with movimientos=p.get_movimientos_ingresos invertir=True %}
						</div>
						<div class="col-lg-6">
						<h4>Gastos</h4>
							{% include "cobranzas/movimientos_table.html" with movimientos=p.get_movimientos_gastos invertir=False %}
						</div>
							{% with p.last_day|date:"d \d\e M Y" as last_day %}
							{% include "cobranzas/saldos_list.html" with label="Saldos al: "|add:last_day cuentas=p.get_saldo_disponibilidades %}
							{% endwith %}
							{% with p.last_day|date:"d \d\e M Y" as last_day %}
							{% include "cobranzas/saldos_list.html" with label="Otros Activos al: "|add:last_day cuentas=p.get_otros_activos %}
							{% endwith %}
					</div>
				</div>
				{% endfor%}
			</div>
		</div>

		<!-- /section:elements.tab.option -->
	</div>

</div>
	
<div class="modal fade in" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" success="">
  <div class="modal-dialog">
	<div class="modal-content">
	</div>
  </div>
</div>
{% endblock %}
	{% block javascript %}


	{% endblock %}